# Create and configure a new API proxy in the API gateway

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: apim-variables

steps:

- script: chmod u+x ./scripts/*.sh
  displayName: 'Grant shell execution permissions'

- script: ./scripts/01_CheckManifest.sh
  displayName: 'Check manifest.json file'

- script: ./scripts/11_CreateAPIDefinition.sh
  displayName: 'Create API definition'
  env:
    APIGW_PASSWORD: $(APIGW_PASSWORD)

- script: ./scripts/14_UpdateAPIMetadata.sh
  displayName: 'Update API metadata'
  env:
    APIGW_PASSWORD: $(APIGW_PASSWORD)